### ISSUE TITLE
[minor ones] Typo found

### ISSUE THREAD

**Issue by chaos234** [TheLMiffy1111/EssentialCraft4Unofficial#49]
Only a small reminder about a type which I found looking through the Items in JEI: https://i.imgur.com/KREB1CS.png

**Comment by luke-bravenboer** [comment]
Uhh, lol... did you even read its entry in the research book (in the '_The world of Hoanna_' chapter)? I'm pretty sure it's intentional.

I'm pretty sure the Darkness O8elisk itself is broken anyway, it doesn't seem to spawn anything for me, and you can't put any items in through the GUI (though it still accepts hopper input)

**Comment by chaos234** [comment]
No, hasn't looked deeper into it to not spoile to much ;)

**Comment by TheLMiffy1111** [comment]
intentional
